apiVersion: apps/v1
kind: Deployment
metadata:
  name: history-service-app
  labels:
    app: history-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: history-service-app
  template:
    metadata:
      labels:
        app: history-service-app
    spec:
      containers:
        - name: history-service-app
          image: ptyagi13/history-service:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8083

---
apiVersion: v1
kind: Service
metadata:
  name: history-service-svc
spec:
  ports:
    - targetPort: 8083
      port: 80
  selector:
    app: history-service-app